# Generated by Django 4.2.5 on 2025-01-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_voucher_master_finish_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_no', models.CharField(max_length=100, unique=True)),
                ('buyer_inv_no', models.CharField(max_length=100)),
                ('company_gst', models.CharField()),
                ('ledger_type', models.CharField(default='sales', max_length=20)),
                ('fright_transport', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gross_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cash_disct', models.DecimalField(decimal_places=3, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
                ('selected_godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.godown_finished_goods')),
            ],
        ),
        migrations.CreateModel(
            name='sales_voucher_finish_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('trade_disct', models.IntegerField()),
                ('spl_disct', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
                ('sales_voucher_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sales_voucher_master_finish_goods')),
            ],
        ),
    ]
