# Generated by Django 4.2.5 on 2025-02-20 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bin_for_raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='rack_for_raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBinAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.bin_for_raw_material')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_creation')),
            ],
            options={
                'unique_together': {('item', 'bin')},
            },
        ),
        migrations.AddField(
            model_name='bin_for_raw_material',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.rack_for_raw_material'),
        ),
        migrations.AddField(
            model_name='item_creation',
            name='bins',
            field=models.ManyToManyField(through='product.ItemBinAssignment', to='product.bin_for_raw_material'),
        ),
    ]
