# Generated by Django 4.2.5 on 2025-03-01 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanmaster',
            name='balance_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverychallanmaster',
            name='total_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales_voucher_finish_goods',
            name='delivery_challan_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.deliverychallanproducts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_voucher_master_finish_goods',
            name='delivery_challans',
            field=models.ManyToManyField(blank=True, to='product.deliverychallanmaster'),
        ),
    ]
