# Generated by Django 4.2.5 on 2025-02-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outward_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_picklist_no', models.IntegerField()),
                ('unique_serial_no', models.CharField(max_length=25, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('bin_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.finished_product_warehouse_bin')),
                ('outward_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outward_product', to='product.outward_product_master')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
            ],
        ),
    ]
