# Generated by Django 4.2.5 on 2025-02-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rack_for_raw_material_bin_for_raw_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rack_for_raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='bin_for_raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_name', models.CharField(max_length=255)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.rack_for_raw_material')),
            ],
        ),
        migrations.AddField(
            model_name='item_creation',
            name='bin',
            field=models.ManyToManyField(to='product.bin_for_raw_material'),
        ),
    ]
