# Generated by Django 4.2.5 on 2025-02-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rack_for_raw_material_bin_for_raw_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallanMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_challan_no', models.CharField(max_length=252, unique=True)),
                ('shipping_address', models.TextField()),
                ('vehicle_no', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('dispatch_time', models.TimeField()),
                ('no_of_boxes', models.PositiveIntegerField()),
                ('no_of_pcs', models.PositiveIntegerField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
            ],
        ),
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='narration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales_voucher_master_outward_scan',
            name='narration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryChallanProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_challan_products', to='product.deliverychallanmaster')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
            ],
        ),
    ]
