# Generated by Django 4.2.5 on 2025-02-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_bin_for_raw_material_rack_for_raw_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_creation',
            name='bins',
        ),
    ]
