# Generated by Django 4.2.5 on 2025-03-01 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_deliverychallanmaster_balance_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_voucher_finish_goods',
            name='delivery_challan_product',
        ),
        migrations.RemoveField(
            model_name='sales_voucher_master_finish_goods',
            name='delivery_challans',
        ),
        migrations.AlterField(
            model_name='deliverychallanproducts',
            name='delivery_challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.deliverychallanmaster'),
        ),
    ]
