# Generated by Django 4.2.5 on 2025-02-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_outward_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outward_products',
            name='outward_picklist_no',
            field=models.CharField(max_length=25),
        ),
    ]
