# Generated by Django 4.2.5 on 2025-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sales_voucher_master_finish_goods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsbinallocation',
            name='outward',
            field=models.BooleanField(default=False),
        ),
    ]
