# Generated by Django 4.2.5 on 2025-02-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_outward_products_outward_picklist_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_return_inward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_return_no', models.CharField(max_length=100)),
                ('ledger_type', models.CharField(default='sales return', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
                ('sales_voucher_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sales_voucher_master_outward_scan')),
                ('selected_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.finished_goods_warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='sales_return_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_serial_no', models.CharField(max_length=25, unique=True)),
                ('scan_qty', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bin_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.finished_product_warehouse_bin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
                ('sales_return_inward_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sales_return_inward')),
            ],
        ),
    ]
