# Generated by Django 4.2.5 on 2025-03-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_sales_voucher_finish_goods_delivery_challan_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_voucher_master_finish_goods',
            name='company_gst',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='SalesVoucherDeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.deliverychallanmaster')),
                ('sales_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sales_voucher_master_finish_goods')),
            ],
            options={
                'unique_together': {('sales_voucher', 'delivery_challan')},
            },
        ),
    ]
