# Generated by Django 4.2.5 on 2025-01-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_finishedgoodsbinallocation_outward'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_product_bin_for_picklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=252)),
                ('model_name', models.CharField(max_length=252)),
                ('product_bin', models.CharField(max_length=252)),
                ('bin_qty', models.IntegerField()),
                ('product_qty', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sales_voucher_master_outward_scan',
            name='sale_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outward_products',
            name='outward_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outward_product', to='product.outward_product_master'),
        ),
    ]
