# Generated by Django 4.2.5 on 2025-03-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_sales_voucher_master_finish_goods_company_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallanproducts',
            name='delivery_challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.deliverychallanmaster'),
        ),
    ]
