# Generated by Django 4.2.5 on 2025-02-14 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_sales_return_inward_sales_return_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_return_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('trade_disct', models.IntegerField()),
                ('spl_disct', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
                ('sales_return_inward_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sales_return_inward')),
            ],
        ),
    ]
