# Generated by Django 4.2.5 on 2025-01-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_temp_product_bin_for_picklist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp_product_bin_for_picklist',
            old_name='product_qty',
            new_name='res_qty',
        ),
        migrations.RemoveField(
            model_name='temp_product_bin_for_picklist',
            name='model_name',
        ),
    ]
