# Generated by Django 4.2.5 on 2025-02-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_sales_return_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_return_voucher',
            name='sales_return_inward_instance',
        ),
        migrations.AlterField(
            model_name='sales_return_inward',
            name='sales_voucher_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.sales_voucher_master_outward_scan'),
        ),
        migrations.AlterField(
            model_name='sales_return_product',
            name='sales_return_inward_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.sales_return_inward'),
        ),
        migrations.CreateModel(
            name='sales_return_voucher_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('sales_return_inward_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.sales_return_inward')),
                ('sales_voucher_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.sales_voucher_master_outward_scan')),
            ],
        ),
        migrations.AddField(
            model_name='sales_return_voucher',
            name='sales_return_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.sales_return_voucher_master'),
            preserve_default=False,
        ),
    ]
