# Generated by Django 4.2.5 on 2025-01-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_qty_temp_product_bin_for_picklist_res_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_product_bin_for_picklist',
            name='product_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
