# Generated by Django 4.2.5 on 2025-02-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_sales_return_voucher_sales_return_inward_instance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outward_products',
            unique_together={('outward_no', 'unique_serial_no')},
        ),
    ]
