# Generated by Django 4.2.5 on 2025-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_temp_product_bin_for_picklist_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_product_bin_for_picklist',
            name='utilize_all',
            field=models.BooleanField(default=False),
        ),
    ]
