# Generated by Django 4.2.5 on 2025-03-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_delivery_challan_quantity_through_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_voucher_finish_goods',
            name='delivery_challan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.deliverychallanmaster'),
            preserve_default=False,
        ),
    ]
