# Generated by Django 4.2.5 on 2025-02-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_outward_products_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outward_products',
            name='unique_serial_no',
            field=models.CharField(max_length=25),
        ),
    ]
