# Generated by Django 4.2.5 on 2025-03-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_sales_voucher_finish_goods_delivery_challan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_voucher_finish_goods',
            name='delivery_challan',
        ),
    ]
