# Generated by Django 4.2.5 on 2025-03-03 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_sales_voucher_finish_goods_delivery_challan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallanmaster',
            name='balance_qty',
        ),
        migrations.RemoveField(
            model_name='deliverychallanmaster',
            name='total_qty',
        ),
        migrations.AddField(
            model_name='deliverychallanproducts',
            name='balance_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesvoucherdeliverychallan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesvoucherdeliverychallan',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesvoucherdeliverychallan',
            name='delivery_challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.deliverychallanmaster'),
        ),
        migrations.AlterField(
            model_name='salesvoucherdeliverychallan',
            name='sales_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sales_voucher_master_finish_goods'),
        ),
    ]
