# Generated by Django 4.2.5 on 2025-02-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_bin_quantity_through_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_voucher_master_outward_scan',
            name='buyer_inv_no',
        ),
    ]
