# Generated by Django 4.2.5 on 2025-02-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_outward_products_unique_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_name', models.CharField(max_length=252)),
            ],
        ),
    ]
