# Generated by Django 4.2.5 on 2025-02-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_salesman_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_voucher_master_outward_scan',
            name='salesman',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='product.salesman_info'),
            preserve_default=False,
        ),
    ]
