# Generated by Django 4.2.5 on 2025-02-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_sales_voucher_master_outward_scan_buyer_inv_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedgoodsbinallocation',
            old_name='outward',
            new_name='outward_done',
        ),
    ]
