# Generated by Django 4.2.5 on 2025-03-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_deliverychallanproducts_balance_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanproducts',
            name='balance_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
