# Generated by Django 4.2.5 on 2025-02-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_sales_voucher_master_outward_scan_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='cash_disct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='company_gst',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='fright_transport',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='grand_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='gross_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='ledger_type',
            field=models.CharField(default='sales', max_length=20),
        ),
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='party_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.ledger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='salesman',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='product.salesman_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_return_voucher_master',
            name='selected_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.finished_goods_warehouse'),
        ),
    ]
