# Generated by Django 4.2.5 on 2025-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_outward_finishedgoodsbinallocation_outward_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_product_bin_for_picklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=252)),
                ('product_bin', models.CharField(max_length=252)),
                ('product_qty', models.IntegerField()),
                ('bin_qty', models.IntegerField()),
            ],
        ),
    ]
