# Generated by Django 4.2.5 on 2025-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_deliverychallanproducts_balance_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_work_in_product_to_item',
            name='dummy_balance_qty',
            field=models.IntegerField(default=0),
        ),
    ]
