# Generated by Django 4.2.5 on 2025-02-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_temp_product_bin_for_picklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_product_bin_for_picklist',
            name='balance_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_product_bin_for_picklist',
            name='bin_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_product_bin_for_picklist',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
    ]
