# Generated by Django 4.2.5 on 2025-02-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_temp_product_bin_for_picklist_balance_qty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_product_bin_for_picklist',
        ),
        migrations.AddField(
            model_name='picklist_voucher_master',
            name='ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.ledger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picklist_voucher_master',
            name='narration',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
