# Generated by Django 4.2.5 on 2025-03-08 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_labour_work_in_product_to_item_dummy_balance_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_goods_stock_transfermaster',
            name='dispatch_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finished_goods_stock_transfermaster',
            name='driver_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finished_goods_stock_transfermaster',
            name='no_of_boxes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finished_goods_stock_transfermaster',
            name='no_of_pcs',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finished_goods_stock_transfermaster',
            name='vehicle_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
