# Generated by Django 4.2.5 on 2025-02-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_delete_temp_product_bin_for_picklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picklist_voucher_master',
            name='ledger',
        ),
        migrations.AddField(
            model_name='picklist_voucher_master',
            name='ledgerTypes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.ledgertypes'),
            preserve_default=False,
        ),
    ]
