# Generated by Django 4.2.5 on 2025-03-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_finished_goods_stock_transfermaster_dispatch_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallanmaster',
            name='dispatch_time',
        ),
    ]
