# Generated by Django 4.2.5 on 2025-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_picklist_voucher_master_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist_voucher_master',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Recieving', 'Recieving'), ('close', 'close')], default='Pending', max_length=50),
        ),
    ]
