# Generated by Django 4.2.5 on 2025-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_picklist_voucher_master_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist_voucher_master',
            name='narration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
