# Generated by Django 4.2.5 on 2025-02-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_picklist_voucher_master_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist_voucher_master',
            name='total_qty',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Picklist_process_in_outward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.picklist_voucher_master')),
            ],
        ),
    ]
