# Generated by Django 4.2.5 on 2025-02-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_picklist_voucher_master_total_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist_process_in_outward',
            name='balance_qty',
            field=models.IntegerField(default=0),
        ),
    ]
