# Generated by Django 4.2.5 on 2025-02-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_picklist_process_in_outward_balance_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist_process_in_outward',
            name='outward_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='outward_product_picklist', to='product.outward_product_master'),
            preserve_default=False,
        ),
    ]
