# Generated by Django 4.2.5 on 2025-02-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_picklist_process_in_outward_outward_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist_process_in_outward',
            name='outward_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.outward_product_master'),
        ),
    ]
