# Generated by Django 4.2.5 on 2025-02-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_picklist_process_in_outward_balance_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist_process_in_outward',
            name='balance_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
