# Generated by Django 4.2.5 on 2024-12-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_alter_purchase_order_for_puchase_voucher_rm_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodsbinallocation',
            name='related_purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_purchase_voucher_items'),
        ),
    ]
