# Generated by Django 4.2.5 on 2024-12-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_purchase_order_master_for_puchase_voucher_rm_voucher_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_voucher_master_finish_goods',
            name='company_gst',
            field=models.CharField(),
        ),
    ]
