# Generated by Django 4.2.5 on 2024-12-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_sales_voucher_master_finish_goods_company_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_purchase_voucher_master',
            name='narration',
            field=models.CharField(default='No narration', max_length=255),
            preserve_default=False,
        ),
    ]
