# Generated by Django 4.2.5 on 2024-12-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_finished_goods_stock_transfermaster_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_goods_stock_transfermaster',
            name='voucher_no',
            field=models.CharField(unique=True),
        ),
    ]
