# Generated by Django 4.2.5 on 2025-01-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_finished_goods_stock_transfermaster_voucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_voucher_master_finish_goods',
            name='selected_godown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.godown_finished_goods'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finished_goods_stock_transfermaster',
            name='narration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
