# Generated by Django 4.2.5 on 2025-01-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_sales_voucher_master_finish_goods_selected_godown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_voucher_master_finish_goods',
            name='selected_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.finished_goods_warehouse'),
        ),
        migrations.AlterField(
            model_name='sales_voucher_master_finish_goods',
            name='selected_godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.godown_finished_goods'),
        ),
    ]
