# Generated by Django 4.2.5 on 2025-01-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_sales_voucher_master_finish_goods_selected_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_voucher_finish_goods',
            name='unique_serial_no',
            field=models.CharField(default='default_serial', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
