# Generated by Django 4.2.5 on 2025-01-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_sales_voucher_finish_goods_unique_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_purchase_voucher_master',
            name='narration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
