# Generated by Django 4.2.5 on 2025-01-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_alter_product_purchase_voucher_master_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_voucher_finish_goods',
            name='unique_serial_no',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
