# Generated by Django 4.2.5 on 2025-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_picklist_voucher_master_picklist_products_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_master_for_puchase_voucher_rm',
            name='po_no',
            field=models.CharField(unique=True),
        ),
    ]
