# Generated by Django 4.2.5 on 2025-01-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_alter_purchase_order_master_for_puchase_voucher_rm_po_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_master_for_puchase_voucher_rm',
            name='po_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
