# Generated by Django 4.2.5 on 2025-01-23 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_alter_purchase_order_master_for_puchase_voucher_rm_po_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_puchase_voucher_rm',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_for_puchase_voucher_rm',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase_order_master_for_puchase_voucher_rm',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_master_for_puchase_voucher_rm',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sales_voucher_finish_goods',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales_voucher_finish_goods',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
