# Generated by Django 4.2.5 on 2025-01-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_purchase_order_for_puchase_voucher_rm_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_puchase_voucher_rm',
            name='demo_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
