# Generated by Django 4.2.5 on 2025-01-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_purchase_order_for_puchase_voucher_rm_demo_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size_in_bin', models.IntegerField(default=0)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_categories', to='product.finished_product_warehouse_bin')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_bins', to='product.maincategory')),
            ],
        ),
    ]
