# Generated by Django 4.2.5 on 2025-01-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_remove_finished_product_warehouse_bin_sub_catergory_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finished_product_warehouse_bin',
            old_name='main_catergory_id',
            new_name='main_catergory',
        ),
    ]
