# Generated by Django 4.2.5 on 2025-01-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_rename_main_catergory_id_finished_product_warehouse_bin_main_catergory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished_product_warehouse_bin',
            name='main_catergory',
        ),
        migrations.AddField(
            model_name='finished_product_warehouse_bin',
            name='sub_catergory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='product.maincategory'),
        ),
    ]
