# Generated by Django 4.2.5 on 2025-01-25 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_remove_finished_product_warehouse_bin_main_catergory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_product_warehouse_bin',
            name='products_in_bin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picklist_products_list',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picklist_products_list',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='BinCategoryAssignment',
        ),
    ]
