# Generated by Django 4.2.5 on 2025-01-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_finished_product_warehouse_bin_products_in_bin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='outward_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picklist_no', models.CharField(max_length=252)),
                ('unique_serial_no', models.CharField(max_length=25, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('bin_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.finished_product_warehouse_bin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
            ],
        ),
    ]
