# Generated by Django 4.2.5 on 2025-01-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_outward_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outward_products',
            name='picklist_no',
        ),
    ]
